### ISSUE TITLE
Can we have an option for different MySQL Port

### ISSUE THREAD

**Issue by crackayus09** [ComputeStacks/docker#1]
As I see from the dockerfile and build script custom MySQL port is yet not supported for WHCMS. Can we have that?

I am interested to contribute.

**Comment by kwatson** [comment]
Hi @crackayus09 -- Yeah sure, I see no problem with that. I just ask that when you add the `--port` flag to the mysql command in the startup script, please create a default value using `3306` so that it's backwards compatible with existing configurations that do not supply the port as an environment variable. 

Feel free to open a pull request with that -- and thank you for contributing!

**Comment by kwatson** [comment]
Hi @crackayus09 -- your PR has been merged.

I apparently misunderstood how the new github CLI works and my changes to your original pull request were not applied, so thats why you see a revert pull request. I ended up just merging locally and pushing.

The original commit I made to your PR is visible here: 618e7b4 

The main issue was that while you were checking for the existence of the `DB_PORT`, that was still generating an unbound variable error. I modified that to use a different syntax that applies a default value instead.

I tested the WHMCS image, both with, and without, supplying a `DB_PORT` and it was successful.
